// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrvyzsVZCtt1zDEsiFO_PgST4UAQ-KtwY',
    appId: '1:272625566351:web:2c5311a7125e4b3872e6fa',
    messagingSenderId: '272625566351',
    projectId: 'globalchat-36f25',
    authDomain: 'globalchat-36f25.firebaseapp.com',
    storageBucket: 'globalchat-36f25.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmF45DFXVua56g5bmlVCmTOzpV8YAEH7Q',
    appId: '1:272625566351:android:945fb5188c61e8a872e6fa',
    messagingSenderId: '272625566351',
    projectId: 'globalchat-36f25',
    storageBucket: 'globalchat-36f25.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoHwzIe_mNobDBeEZPi6MfxcWe-aoMWe0',
    appId: '1:272625566351:ios:4a2fa7995e56a89a72e6fa',
    messagingSenderId: '272625566351',
    projectId: 'globalchat-36f25',
    storageBucket: 'globalchat-36f25.firebasestorage.app',
    iosBundleId: 'com.dummyapps.globalchat',
  );
}
